FROM node:18-bullseye-slim AS builder


WORKDIR /app

ARG APP_NAME=angular-15-crud
ENV APP_NAME=${APP_NAME}

COPY package.json package-lock.json* ./

RUN if [ -f package-lock.json ]; then npm ci --silent; else npm install --silent; fi

COPY . .

RUN npm run build -- --configuration production

FROM nginx:stable-alpine AS runtime

RUN rm -rf /usr/share/nginx/html/*

COPY nginx.conf /etc/nginx/conf.d/default.conf

ARG APP_NAME=angular-15-crud
COPY --from=builder /app/dist/${APP_NAME} /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
